name: publish
description: Publish an artifact.
inputs:
  working-directory:
    description: Working directory to run the publish command in.
    required: false
    default: .

  snap-track:
    description: Snap track.
    required: false
    default: latest

  rock-registry:
    description: Container registry for rocks.
    required: false
    default: ghcr.io
  rock-architectures:
    description: JSON array of rock architectures.
    required: false
    default: '["amd64"]'

  charm-channel:
    description: Charmhub channel.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Release artifact
      shell: bash
      run: |
        just working-directory=${{ inputs['working-directory'] }} publish
      env:
        SNAP_FILE: ${{ inputs['snap-file'] }}
        SNAP_BRANCH_NAME: ${{ inputs['snap-branch-name'] }}
        SNAP_TRACK: ${{ inputs['snap-track'] }}
        ROCK_FILE: ${{ inputs['rock-file'] }}
        ROCK_REGISTRY: ${{ inputs['rock-registry'] }}
        ROCK_ARCHITECTURES: ${{ inputs['rock-architectures'] }}
        CHARM_FILE: ${{ inputs['charm-file'] }}
        CHARM_CHANNEL: ${{ inputs['charm-channel'] }}
