name: Notary CI/CD Workflow (This is an example workflow to illustrate how one would use the shared CI/CD workflows)

on:
  push:
    branches: ["!main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: run shared workflow
        uses: ./.github/actions/prepare@v3
        env:
          TOOLCHAINS: "go typescript rockcraft snapcraft"
          TYPESCRIPT_WORKING_DIRECTORY: "ui"

  cd:
    strategy:
      fail-fast: false
      matrix:
        runner:
          [
            self-hosted-linux-amd64-noble-medium,
            self-hosted-linux-arm64-noble-medium,
          ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: run shared workflow
        uses: ./.github/workflows/continuous-delivery.yaml


name: continuous-integration
on:
  workflow_call:
    secrets:
      EXAMPLE_SECRET:
        description: "this secret comes from the repo"
        required: true
    inputs:
      stategy-overrides:
        type: string
        description: "Overrides for CI strategy. Look at the REAMDME.md for more details"
        required: true
    outputs:
      logs:
        description: "logs for all collected runs"
        value: "example output value"

jobs:
  continuous-integration:
    name: Continuous Integration
    needs: validate-ci-configuration
    env:
      overrides: ${{ needs.validate-ci-configuration.outputs.overrides }}

    strategy:
      fail-fast: true
      matrix: ${{ fromJson(overrides.validate-ci-configuration.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: .github/actions/prepare
      - name: run continuous integration
        shell: bash
        run: |
          just ci
      - name: upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: ci-logs #todo

      # Forward logs to dashboard for analytics TODO: add to readme: https://documentation.ubuntu.com/self-hosted-runners/en/latest/usage/observability/#forward-custom-log-files-from-a-workflow
      - uses: canonical/github-runner-operators/actions/enable-log-forwarding@4e4df51
        with:
          files: |
            /var/log/chrony/*.log
            /var/log/syslog
