name: Release Please
run-name: release ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        with:
          token: ${{ secrets.PAT_TOKEN || github.token }}
          target-branch: ${{ inputs.target-branch }}
          config-file: ${{ inputs.config-file }}
          manifest-file: ${{ inputs.manifest-file }}
          include-component-in-tag: ${{ inputs.include-component-in-tag }}
