name: Identify KEVs

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: false
        type: string
        description: "This should match the ref that you called the workflow with. It ensures that the scripts are run from the same commit as the workflow."

jobs:
  identify-kevs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: canonical/identity-credentials-workflows
          path: identity-credentials-workflows
          ref: ${{ inputs.checkout_ref }}
      # NOTE: stderr is redirected to /dev/null to avoid leaking information to
      # public workflow output but the scripts can still be used locally to debug
      - name: Identify CVEs in KEV Database
        run: ./identity-credentials-workflows/kev-identification/identify-kevs.sh ${{ github.repository }} > cves.txt 2>/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create SARIF
        run: ./identity-credentials-workflows/kev-identification/create-sarif.sh <cves.txt >cves.sarif 2>/dev/null
      - name: Upload SARIF
        run: ./identity-credentials-workflows/kev-identification/upload-sarif.sh cves.sarif ${{ github.repository }} 2>/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


