name: Identify KEVs

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  identify-kevs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: canonical/identity-credentials-workflows
          path: identity-credentials-workflows
          ref: ${{ github.workflow_sha}}  # Make sure to use the same ref as the calling workflow, so that we're getting the code from the same commit as the yaml.
      # NOTE: stderr is redirected to /dev/null to avoid leaking information to
      # public workflow output but the scripts can still be used locally to debug
      - name: Identify CVEs in KEV Database
        run: ./identity-credentials-workflows/kev-identification/identify-kevs.sh ${{ inputs.repo }} > cves.txt 2>/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create SARIF
        run: ./identity-credentials-workflows/kev-identification/create-sarif.sh <cves.txt >cves.sarif 2>/dev/null
      - name: Upload SARIF
        run: ./identity-credentials-workflows/kev-identification/upload-sarif.sh cves.sarif ${{ inputs.repo }} 2>/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


