name: Lint report

on:
  workflow_call:
    inputs:
      path:
        description: Path to the charm's root directory
        required: false
        type: string
        default: ./

jobs:
  lint-report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        run: sudo snap install --classic astral-uv

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run tests using tox
        run: |
          cd ${{ inputs.path }}
          tox -e lint
