name: Lint report

on:
  workflow_call:
    inputs:
      path:
        description: Path to the charm's root directory
        required: false
        type: string
        default: ./

jobs:
  lint-report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        run: sudo snap install --classic astral-uv

      - name: Run tests using tox
        run: |
          cd ${{ inputs.path }}
          uv tool install tox --with tox-uv
          tox -e lint
