name: Release Please

on:
  push:
    branches:
      - v0

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@8bb7a2ed0f90c9802c83129a9488d235a1f31a7c
        with:
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json 