name: TICS Server
on:
  workflow_call:

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: generate coverage
        run: |
          go install github.com/t-yuki/gocover-cobertura@latest
          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          go test -v ./... -coverprofile=coverage.out
          gocover-cobertura < coverage.out > coverage.xml
      - name: move results to necessary folder for TICS
        run: |
          mkdir .cover
          mv coverage.xml .cover/coverage.xml
      - name: TICSQserver Analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: notary
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
