name: Unit tests

on:
  workflow_call:
    inputs:
      path:
        description: Path to the charm's root directory
        required: false
        type: string
        default: ./

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        run: sudo snap install --classic astral-uv
      
      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run tests using tox
        run: |
          cd ${{ inputs.path }}
          tox -e unit
