name: Unit tests

on:
  workflow_call:
    inputs:
      path:
        description: Path to the charm's root directory
        required: false
        type: string
        default: .
      fetch-libs:
        description: Run charmcraft fetch-libs before unit tests
        required: false
        default: false
        type: boolean

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install charmcraft
        if: ${{ inputs.fetch-libs }}
        run: sudo snap install charmcraft --classic

      - name: Fetch charmcraft libs
        if: ${{ inputs.fetch-libs }}
        run: charmcraft fetch-libs
        working-directory: ${{ inputs.path }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Install uv
        run: sudo snap install --classic astral-uv

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run tests using tox
        run: tox -e unit
        working-directory: ${{ inputs.path }}
